# Site settings
title: Alexander O&apos;Connor 
email: dralexoconnor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Professional Site for Dr. Alexander O&apos;Connor
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uberalex.github.io" # the base hostname & protocol for your site
twitter_username: uberalex 
github_username: uberalex 

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
